---
# tasks file for backports
- name: add repo
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports
    update_cache: yes
  when: (ansible_distribution_release == 'jessie') or
        (ansible_distribution_release == 'wheezy') or
        (ansible_distribution_release == 'stretch') or
        (ansible_distribution_release == 'bullseye')
